NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="KOINLY.SITE"
ORG_URL="https://koinly.site"
ORG_LOGO="https://koinly.site/logo.png"
ORG_DESCRIPTION="Perfect For Crypto Investors"

[[CURRENCIES]]
code="AL12454320A"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="AL12454320A"
status="live"
display_decimals=7

[[CURRENCIES]]
code="BULLION"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="BULLION"
status="live"
display_decimals=7

[[CURRENCIES]]
code="DAG"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="DAG"
status="live"
display_decimals=7

[[CURRENCIES]]
code="FRANKLIN"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="FRANKLIN"
status="live"
display_decimals=7

[[CURRENCIES]]
code="ICE"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="ICE"
status="live"
display_decimals=7

[[CURRENCIES]]
code="SERIES1996"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="SERIES1996"
status="live"
display_decimals=7

[[CURRENCIES]]
code="WLFI"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="WLFI"
status="live"
display_decimals=7

[[CURRENCIES]]
code="XRPBANK"
issuer="GATSE2E74QAGQYUVC2ZDTJNMAYBEUHXZAQXYTAPNPPKP5IAH7AUODSMI"
name="XRPBANK"
status="live"
display_decimals=7
