NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME=""
ORG_URL=""
ORG_LOGO=""
ORG_DESCRIPTION=""

[[CURRENCIES]]
code=""
issuer=""
name=""
desc=""
display_decimals=7
image=""
status="live"
